---

- name: ChangeWndSize16777216-Local1
  command: chmod 666 /etc/sysctl.conf 
  become: yes

- name: ChangeWndSize16777216-Local2
  command: sed -i '/net.ipv4.tcp_rmem/d' /etc/sysctl.conf
  become: yes

- name: ChangeWndSize16777216-Local3
  command: sed -i '/net.ipv4.tcp_wmem/d' /etc/sysctl.conf
  become: yes

- name: ChangeWndSize16777216-Local4
  command: echo "net.ipv4.tcp_rmem = 8760  256960  16777216" >> /etc/sysctl.conf
  become: yes

- name: ChangeWndSize16777216-Local5
  command: echo "net.ipv4.tcp_wmem = 8760  256960  16777216" >> /etc/sysctl.conf
  become: yes

- name: ChangeWndSize16777216-Local6
  command: /sbin/sysctl -p
  become: yes

- name: ChangeWndSize16777216-Local7
  command: chmod 644 /etc/sysctl.conf
  become: yes

- name: ChangeWndSize16777216-Remote1
  command: ssh ansible@{{ targetHost }} -p 10022 sudo sed -i '/net.ipv4.tcp_rmem/d' /etc/sysctl.conf

- name: ChangeWndSize16777216-Remote2
  command: ssh ansible@{{ targetHost }} -p 10022 sudo sed -i '/net.ipv4.tcp_wmem/d' /etc/sysctl.conf

- name: ChangeWndSize16777216-Remote3
  command: ssh ansible@{{ targetHost }} -p 10022 sudo sed -i '\$a\net.ipv4.tcp_rmem\ =\ 8760\ \ 256960\ \ 16777216' /etc/sysctl.conf

- name: ChangeWndSize16777216-Remote4
  command: ssh ansible@{{ targetHost }} -p 10022 sudo sed -i '\$a\net.ipv4.tcp_wmem\ =\ 8760\ \ 256960\ \ 16777216' /etc/sysctl.conf


- name: ChangeWndSize16777216-Remote5
  command: ssh ansible@{{ targetHost }} -p 10022 sudo /sbin/sysctl -p